### ISSUE TITLE
Narration Edits

### ISSUE THREAD

**Issue by Kisselphil** [vmasc-odu/Virginia-Philosophy-Reality-Lab#14]
**Describe the Adjustment**
Additional narration to provide greater context during the module.

What follows is @Kisselphil's suggestions for edits to the narration for clarity and simplicity. Existing narration is as of 3/8/21.  Bold/ italics are suggested additions and changes.  Audio clips with suggested changes have been given a checkbox.

Narration: 

- "Thank you for participating in this Virginia Philosophy Reality Labs project. We appreciate your support and commitment towards research. As you have already read through and agreed to the IRB documentation, and thus agreeing to this study we want to make sure of a few things before we start the process. At any given point when you hear this 'tone' we will be fading your experience and physically moving your virtual self into another region of the environment. This is to hopefully reduce motion sickness and notify you prior to this occurring. This is a fully virtual reality experience that utilizes controller based user input. You will be able to interact with some aspect of your environment, teleport between defined locations, and at times engage with other items within the environment. Thank you again and your journey starts now..." (tone)

 - [x] “Before we begin, please explore the office.  You have a few minutes here to get comfortable with the interactions.  When you’re ready to move on, please see the computer screen on the desk.  You’ll need to input your survey code.  Don’t have a survey code?  See the link on the screen for more information.  _**You can also open the menu on your watch if you have questions.**_ Thanks, and good luck on your training.” see #7 for updates here

- “Thanks for swinging by to help us test our new rail system. As you’ve probably noticed, we’re still working on the project, so you might see some workers making adjustments to the track. The monorail is fully automated, so there’s no one on board the trains. Today we're going to test our backup systems in case human intervention is ever needed. That’s where you come in.”

- “As a control booth operator you are provided with closed caption tv's. All instructions will come from our public PA system and be displayed on the screen. This screen will show you a camera feed from one of the selected cameras. Each camera shows one of the two tracks the train can go down.  Please select a different camera feed now.”

~~- [ ]  **_MAKE ONLY TWO CAMERA FEEDS_**~~ see #11 

- "...great, now that you understand how to switch the camera feeds, lets explain more about the interactive control board. This board visually provides you with information about the main switch and indicates which track is currently active <3 second pause unlock switch event fired> that sound was the switch being unlocked, notice the control board status. You can now utilize the large switch by reaching out and pulling on it... please do this now..."

- *Pulls switch* “... great, notice the track has changed and the train is now routed towards the control booth... "

- “Train engineer here you can make changes to the track up until the train reaches the road intersection, at that point the built-in safety system will lock the switch... as a train approaches you will hear the warning bell <leave 3 second pause here for the warning bell loop> and the board will show you the current position of the approaching train <leave 3 second pause here for flash yellow light on board>.... for training purposes we are now going to send an automated train down the track. Why don't you send the train towards the bridge?"

- a.	*On Success* "Great! You now understand how the control board and switch system work" 
b.	*On Failure* "Looks like you chose not to send the train towards the bridge. That's fine too, as long as you are aware of your decisions."

- [x] "In some rare cases, the switch mechanical system fails. When this occurs, you will hear the failure alarm <leave a 3 second pause here for failure alarm loop> and the ~board~ **_switch_** will be locked out for the next few minutes until the system has reset.

- [x] “Train engineer here we are performing some electrical maintenance for the next few minutes <3 second pause for electrical update sound> Notice the board system status. please take a look..." (had to record for continuity)

- [x] "... those system status lights will let you know if the switch system is operational. During this time you can utilize the water barrels on the walkway as a failsafe if you want to stop a train.  **_Take a look at the water barrels to your right._**”

- [x]  "... Just push a barrel into the path of the train to bring it to a halt.  **_Please try pushing one of the barrels now.”_**

- [x] "The liquid in the barrel creates a temporary electrical short that engages the train's brakes. Honestly, you could really push anything filled with liquid on the walkway into the train's path and it will stop... **_like a big water balloon, or even a person!”_**

- [x] **_“Okay, we’re going to send another train your way.  Please stop the train by pushing the barrel before the train reaches the control tower.”_** ~~(Remove the explosion here.)~~ see  #9 
 
- [x] *If Success   **_"Great! The emergency system override has engaged and you have stopped the train._** We'll send a worker up with another barrel for you shortly..."

- [x] *If Failure "Looks like you didn't activate the emergency stop system.  **_That’s fine too, as long as you are aware of your decisions.  We'll send a worker up with another barrel for you shortly...”_**

- [x] **_“Alright, your training is complete, you’re on your own now.  We’re sending some workers to do maintenance on both tracks, you should see them shortly.  We don’t expect any trains to come, but why don’t you stay in the control booth for a little longer, just in case.”_**

**Comment by JShull** [comment]
Recorded all updates - need to now update the CC text files and the timing parameters tied to the CC subtitles.

**Comment by JShull** [comment]
Had to add two new end recordings - given that half our participants won't see the "push the person" and get the 5 v 1 I updated two new ending recordings to ask why they either pulled the switch or didnt pull the switch

**Comment by JShull** [comment]
Need to append a new Timeline asset to read "Okay, we’re going to send another train your way. Please stop the train by pushing the barrel before the train reaches the control tower." with CCTV and Goal Text

**Comment by JShull** [comment]
Last audio narration has been added for the original replacement/updated audio narration.
