### ISSUE TITLE
Control Booth Pillars

### ISSUE THREAD

**Issue by Kisselphil** [vmasc-odu/Virginia-Philosophy-Reality-Lab#3]
**Describe the Adjustment**
_Move the pillar to the left of the control board in the control booth so it does not block view of the tunnel._

**Things to Consider**
Guideline of information needed:
1. Where are you in the experience? (Just loaded up, was in the office, was at the control booth, etc)
_In the control booth_

2. What object/item specifically are we thinking of adjusting? (Handle on the deck, button at the office, barrel at the tower)
_When you look to the left when standing  in front of the control board, your view of the tunnel is obscured by the pillar/ dividing piece between the windows._

3. Is this a time based adjustment? (Between the first and second train we need 5 extra seconds)
_No_
4. Is this a bug? (I get stuck between training and the first train) Please fill out the bug template instead, that can be found [at the bug template](https://github.com/vmasc-odu/Virginia-Philosophy-Reality-Lab/issues/new?assignees=JShull&labels=bug&template=bug---crash-report.md&title=) :grey_exclamation:
_No_

**Additional context**
_I think there are lots of easy solutions, we could take the whole top off the control booth so it is open air (and no windows); we could change the shape of the control booth so there is no pillar there; etc.  The important thing in my mind is an unimpeded sight line from the teleportation point in front of the control board to the tunnel that the train comes from_

**Comment by JShull** [comment]
I am open to redesigning the top of the control booth to being like a 180 degree "window" in which there are no direct line of sites blocking the views but some element of 'opening areas' so we can still push our person on the tracks.

**Comment by Kisselphil** [comment]
That sounds perfect if it’s not going to be too much work.

**Comment by JShull** [comment]
This has been finished - and is on an active Branch right now should see the updates after I finish the next animation sequence.
