### ISSUE TITLE
Data Full Exhaustive List

### ISSUE THREAD

**Issue by JShull** [vmasc-odu/Virginia-Philosophy-Reality-Lab#31]
# Study CheckList
:o: Go for it!
:hourglass: Working on it
 :bug: A Bug
✔️ Complete

|	Status <br> :o: :hourglass:  :bug: :heavy_check_mark:	|	Assigned To	|	Qualtrics Code	|	Study Type	|	Handle Training	|	Barrel Training	|	Moral Control Result	|	Study Result	|
|	---	|	---	|	---	|	---	|	---	|	---	|	---	|	---	|
|	:bug: 🔧 	|	@KisselPhil	|	100000	|	Switch	|	Bridge	|	Barrel Push	|	Pass	|	Kill 1	|
|	✔️	|	@KisselPhil	|	100002	|	Switch	|	Curve	|	Barrel Push	|	Pass	|	Kill 1	|
|	✔️	|	@KisselPhil	|	100004	|	Switch	|	Bridge	|	No Barrel	|	Pass	|	Kill 1	|
|	✔️|	@KisselPhil	|	100006	|	Switch	|	Curve	|	No Barrel	|	Pass	|	Kill 1	|
|	✔️	|	@KisselPhil	|	100008	|	Switch	|	Bridge	|	Barrel Push	|	Fail	|	Kill 1	|
|	 :bug:|	@KisselPhil	|	100010	|	Switch	|	Curve	|	Barrel Push	|	Fail	|	Kill 1	|
|	✔️  |	@KisselPhil	|	100012	|	Switch	|	Bridge	|	No Barrel	|	Fail	|	Kill 1	|
|	:o:	|	@KisselPhil	|	100014	|	Switch	|	Curve	|	No Barrel	|	Fail	|	Kill 1	|
|	:o:	|	@KisselPhil	|	100016	|	Switch	|	Bridge	|	Barrel Push	|	Pass	|	Kill 5	|
|	:o:	|	@KisselPhil	|	100018	|	Switch	|	Curve	|	Barrel Push	|	Pass	|	Kill 5	|
|	:o:	|	@KisselPhil	|	100020	|	Switch	|	Bridge	|	No Barrel	|	Pass	|	Kill 5	|
|	✔️ 	|	@Jshull	|	100022	|	Switch	|	Curve	|	No Barrel	|	Pass	|	Kill 5	|
|	✔️  	|	@Jshull	|	100024	|	Switch	|	Bridge	|	Barrel Push	|	Fail	|	Kill 5	|
|	✔️  	|	@Jshull	|	100026	|	Switch	|	Curve	|	Barrel Push	|	Fail	|	Kill 5	|
|	:o:	|	@Jshull	|	100028	|	Switch	|	Bridge	|	No Barrel	|	Fail	|	Kill 5	|
|	:o:	|	@Jshull	|	100030	|	Switch	|	Curve	|	No Barrel	|	Fail	|	Kill 5	|
|	⭕ |	@Jshull	|	300001	|	Push	|	Bridge	|	Barrel Push	|	Pass	|	Kill 1	|
|	:o:	|	@Jshull	|	300003	|	Push	|	Curve	|	Barrel Push	|	Pass	|	Kill 1	|
|	:o:	|	@Jshull	|	300005	|	Push	|	Bridge	|	No Barrel	|	Pass	|	Kill 1	|
|	:o:	|	@Jshull	|	300007	|	Push	|	Curve	|	No Barrel	|	Pass	|	Kill 1	|
|	:o:	|	@Jshull	|	300009	|	Push	|	Bridge	|	Barrel Push	|	Fail	|	Kill 1	|
|	:o:	|	@Jshull	|	300011	|	Push	|	Curve	|	Barrel Push	|	Fail	|	Kill 1	|
|:bug:	|	@Krechowicz	|	300013	|	Push	|	Bridge	|	No Barrel	|	Fail	|	Kill 1	|
|:bug:	|	@Krechowicz	|	300015	|	Push	|	Curve	|	No Barrel	|	Fail	|	Kill 1	|
|	🐛 	|	@Krechowicz	|	300017	|	Push	|	Bridge	|	Barrel Push	|	Pass	|	Kill 5	|
|	:o:	|	@Krechowicz	|	300019	|	Push	|	Curve	|	Barrel Push	|	Pass	|	Kill 5	|
|	:o:	|	@Krechowicz	|	300021	|	Push	|	Bridge	|	No Barrel	|	Pass	|	Kill 5	|
|	:o:	|	@Krechowicz	|	300023	|	Push	|	Curve	|	No Barrel	|	Pass	|	Kill 5	|
|	:o:	|	@Krechowicz	|	300025	|	Push	|	Bridge	|	Barrel Push	|	Fail	|	Kill 5	|
|	:o:	|	@Krechowicz	|	300027	|	Push	|	Curve	|	Barrel Push	|	Fail	|	Kill 5	|
|	:o:	|	@Krechowicz	|	300029	|	Push	|	Bridge	|	No Barrel	|	Fail	|	Kill 5	|
|	:o:	|	@Krechowicz	|	300031	|	Push	|	Curve	|	No Barrel	|	Fail	|	Kill 5	|

**Comment by JShull** [comment]
@KRechowicz and @Kisselphil 

This is the only way I could think of keeping track of this. 
Edit the issue to update the status and just use the markdown format to change the icon

**Comment by Kisselphil** [comment]
Bug Report- Qualtrics Code 100000- Closing audio question asked me why I chose NOT to pull the switch, even though I chose to pull the switch

**Comment by JShull** [comment]
> Bug Report- Qualtrics Code 100000- Closing audio question asked me why I chose NOT to pull the switch, even though I chose to pull the switch

Can confirm that the data was pulled correctly and matches what you said. Killed 1 save the 5 aka did pull the switch. Looking into your event logs now to see if I can trace the last piece of that process = best guess right now, old code item still has hooks and is coming right after the new modifications I made this past week.

**Comment by JShull** [comment]
> > Bug Report- Qualtrics Code 100000- Closing audio question asked me why I chose NOT to pull the switch, even though I chose to pull the switch
> 
> Can confirm that the data was pulled correctly and matches what you said. Killed 1 save the 5 aka did pull the switch. Looking into your event logs now to see if I can trace the last piece of that process = best guess right now, old code item still has hooks and is coming right after the new modifications I made this past week.

Found the issue - when I renamed some items this week one of the items was referenced in a public event - this has been fixed - going to confirm on my end by repeating 100000 and will then provide and updated APK @Kisselphil

**Comment by KRechowicz** [comment]
Red text on the screen sometimes overlaps the captions.

**Comment by KRechowicz** [comment]
I know it may be late but captions to fulfill the purpose should be always in front of me. When I don't look at the screen I cannot see what is being said. This potentially should be an option controlled from the watch

**Comment by KRechowicz** [comment]
300013 The oculus button doesn't position me in front of the computer. I need to rotate my chair

**Comment by KRechowicz** [comment]
300013 I didn't know to look where the barrels are and I saw the person at the last second the train was about to go into the curve, so I reacted without thinking.

**Comment by KRechowicz** [comment]
300013 I was confused while taking the survey. Question 1 and 2 I didn't know the difference. Where is the question about assistive tech?

**Comment by KRechowicz** [comment]
300013 second run: Bridge Training: YES, Barrel training: YES (@Kisselphil said I need to push when I am asked to push), MC: Fail, Study result: Barrel was replenished, then the worker showed up, went through the barrel on the right, to the empty spot on the right and fell on the tracks without me pusing.

**Comment by Kisselphil** [comment]
200008- Not a bug, but perhaps an issue.  I pushed the barrel during training EXTREMELY early, and the train stopped when  it had barely left the tunnel.  This may be a problem for the experiment as it could imply that pushing the person on to the track could stop it without killing him.

**Comment by JShull** [comment]
> 200008- Not a bug, but perhaps an issue.  I pushed the barrel during training EXTREMELY early, and the train stopped when  it had barely left the tunnel.  This may be a problem for the experiment as it could imply that pushing the person on to the track could stop it without killing him.

I can reduce this time. At the moment there's a small collision box just before the tunnel that activates the barrel manager to "release" I can move this up. This then reduces the window of decision making. If you have a spatial way of conceptualizing this that would be helpful. E.g. how much distance between guy on the track and the train is needed. Currently I believe I've matched the time/distance associated with barrel training and pushing guy but this is something I should also double check.

**Comment by Kisselphil** [comment]
> > 200008- Not a bug, but perhaps an issue.  I pushed the barrel during training EXTREMELY early, and the train stopped when  it had barely left the tunnel.  This may be a problem for the experiment as it could imply that pushing the person on to the track could stop it without killing him.
> 
> I can reduce this time. At the moment there's a small collision box just before the tunnel that activates the barrel manager to "release" I can move this up. This then reduces the window of decision making. If you have a spatial way of conceptualizing this that would be helpful. E.g. how much distance between guy on the track and the train is needed. Currently I believe I've matched the time/distance associated with barrel training and pushing guy but this is something I should also double check.

Is it the barrel push that triggers the train stopping?  I would like it if you could push the barrel as early as you would like (the current timing on that front is great), but that the train always stops on the curve in front of tower.  That way,  we ensure that the main you push off the tower would  HAVE to get hit (and die)  in order for the train to stop.  

Possibility: pushing the barrel triggers a collider to appear just below the tower on the tracks.  The train then stops when it enters the collider.

**Comment by KRechowicz** [comment]
300015 ST: Push, HT: Bridge instead of Curve, Barrel T: Barrel instead of No Barrel, MC: Fail, The worker fell by himself after passing through the barrel on the right. 

Issue: 5 workers stayed in red on the screen after the MC.

**Comment by KRechowicz** [comment]
300017 ST: Push, HT: Bridge, BT: Push, MC: Fail **I thought that it is for the study result so I let the train kill them so it should be PASS on my end**, SR: I couldn't let them die because the worker fell and blocked the train. I am retaking it again because of my mistake with MC. :)

**Comment by JShull** [comment]
> > > 200008- Not a bug, but perhaps an issue.  I pushed the barrel during training EXTREMELY early, and the train stopped when  it had barely left the tunnel.  This may be a problem for the experiment as it could imply that pushing the person on to the track could stop it without killing him.
> > 
> > 
> > I can reduce this time. At the moment there's a small collision box just before the tunnel that activates the barrel manager to "release" I can move this up. This then reduces the window of decision making. If you have a spatial way of conceptualizing this that would be helpful. E.g. how much distance between guy on the track and the train is needed. Currently I believe I've matched the time/distance associated with barrel training and pushing guy but this is something I should also double check.
> 
> @JShull Is it the barrel push that triggers the train stopping? It would be good if you could push the barrel as early as you would like (the current timing on that front is great), but that the train always stops on the curve in front of tower. That way, we ensure that the man you push off the tower would HAVE to get hit (and die) in order for the train to stop.
> 
> Possibility: pushing the barrel triggers a collider to appear just below the tower on the tracks. The train then stops when it enters the collider.

Realized what you wanted - this is going to take more work. I got pretty creative in timing some stuff tied to when we "touched" something vs. when the item hit vs when we stopped the train. By altering this I just have to test a few items to make sure my timing doesn't get messed up - but totally makes sense and needs to be in before the IRB. Should have this in Sunday Night.

**Comment by JShull** [comment]
> 300013 Red text on the screen sometimes overlaps the captions.

This is now fixed in the updated version.

**Comment by JShull** [comment]
> 300015 ST: Push, HT: Bridge instead of Curve, Barrel T: Barrel instead of No Barrel, MC: Fail, The worker fell by himself after passing through the barrel on the right.
> 
> Issue: 5 workers stayed in red on the screen after the MC.
> 
> Took 300015 again to see if what happens when I don't push the barrel when the train is coming. Didn't finish the second run once I found out :)

Fixed all text on screen/board not reflecting actual status.

**Comment by JShull** [comment]
Going to kill this issue as all of these original fantastic items were addressed
