### ISSUE TITLE
Test test

### ISSUE THREAD

**Issue by KRechowicz** [vmasc-odu/Virginia-Philosophy-Reality-Lab#33]
# Beta Testing #

* There are two active paths you can take to help us beta test this experience. 
* We will give you 2 unique codes to test both paths, one will be an even number and one will be an odd number.
  * If you enter in an even number you will be participating in the **switch** study.
  * If you enter in an odd number you will be participating in the **push** study. 
* Please attempt to answer the following questions to the best of your acknowledgement.

## Equipment Details ##

- [x] Oculus Quest 1
- [ ] Oculus Quest 2
- [ ] Oculus Qust Rift S
- [x] Oculus OG 🕶️

### Estimated Time ###

> Please provide the rough time you started the experience and use time zones, e.g. *12:30am EST May 4, 2021*

### Qualtrics Code ###

> Please enter the 6 digit number you used here e.g. '123456'

### Training Decision on Pulling the Switch ###

- [ ] Followed Directions: sent the train towards the bridge 🌉
- [ ] You Caused Trouble: sent the train towards the curve 

### Training Decision on Stopping the Train with the Barrel ###

- [ ] Followed Directions: pushed the barrel to stop the train
- [ ] You Caused Trouble: did not push the barrel and the system took over

### Moral Control Decision ###

*Switch Study*
- [ ] You sent the train away from the people
- [ ] You did nothing and the five people died 🤯
- [ ] You did nothing and the five people lived 🐛

*Push Study*
- [ ] You stopped the train with a Barrel
- [ ] You did nothing and the five people died 🤯
- [ ] You did nothing ahd the five people lived 🐛

### Study Outcome ###

*Switch Study*
- [ ] You pulled the switch, killed 1, saved 5
- [ ] You did *not* pull the switch, killed 5

*Push Study*
- [ ] You pushed a person, killed 1, saved 5
- [ ] You did *not* push a person, killed 5

### System Crash ##
- [ ] Did you Encounter a Crash?
> Please explain what happened, do you remember if you were interacting with anything? Do you remember about where you were in the experience?
> If you want to be real helpful 🥰 and you think you can recreate the crash and know how to run adb logcat please dump us the file here! 
> If not no worries, we still 🖤 you.

### Additional Details ###

>Any other feedback? Notes? Suggestions? Little things you noticed? Anything?! Please and thank you!😺

**Comment by JShull** [comment]
Thanks for your input - we will process this information and at any point if you have any questions let me know!
