### ISSUE TITLE
View Reset

### ISSUE THREAD

**Issue by Kisselphil** [vmasc-odu/Virginia-Philosophy-Reality-Lab#4]
**Describe the Adjustment**
Make it so that holding down the Oculus button resets the view in the direction the user is facing.

**Things to Consider**
Guideline of information needed:
1. Where are you in the experience? (Just loaded up, was in the office, was at the control booth, etc)
_This occurs throughout the experience, but is particularly acute in the office and in the control booth_
2. What object/item specifically are we thinking of adjusting? (Handle on the deck, button at the office, barrel at the tower)
_No objects.... possibly the camera?_
3. Is this a time based adjustment? (Between the first and second train we need 5 extra seconds)
_No_
4. Is this a bug? (I get stuck between training and the first train) Please fill out the bug template instead, that can be found [at the bug template](https://github.com/vmasc-odu/Virginia-Philosophy-Reality-Lab/issues/new?assignees=JShull&labels=bug&template=bug---crash-report.md&title=) :grey_exclamation:
_Maybe?  _

**Additional context**
Standing in front of the computer in the office, I am not facing the computer.  I try to face the computer and hold down the oculus button to reset view, and it resets in a random direction.  I don't know if this is a bug, or something that we haven't set yet, but it's making it difficult to face and interact with the controls throughout the experience.

**Comment by JShull** [comment]
I have some code that tries to auto-align you when you tele-port. This is causing the problem. I am going to nix that code and then activate the Oculus feature to "re-center" you.

**Comment by Kisselphil** [comment]
Auto-align would have been nice, but c'est la vie.

**Comment by JShull** [comment]
Auto-align has been removed. Re-aligning your experience is a little funky inside MRTK... looking to see if I can just recenter you back on the last teleport you were on - as in our case we control all teleports manually anyways and I have all the code to do this just need to add a new MRTK event/input listener for a controller input hold. This cannot be the Oculus right controller menu button as that defaults to Oculus - should be able to do this with the left controller button - will actually do two events. 

Hold for reset ==> Move you back forward center lock on teleport.
Tap ==> opens menu

**Comment by JShull** [comment]
This issue has been resolved and closed based on the comments from 10 days ago. 1.5 second menu hold results in a faked MRTK reset - MRTK doesn't allow direct camera manipulation but you can adjust the greater parent root object. This is done by setting the 'true zero' to be the last teleport item we landed on plus the rotation based around the world forward z axis. 

With that information we can calculate the delta angle between the user and the parent and then the user and the defined zero - with that information at hand we can always have the user face 'true north' and relocate their local position by always adjusting the difference from that camera position and zero point and then applying that offset to the root parent.
