### ISSUE TITLE
Decrease Switch Pull Length

### ISSUE THREAD

**Issue by Kisselphil** [vmasc-odu/Virginia-Philosophy-Reality-Lab#5]
**Describe the Adjustment**
Decrease distance of switch pull

**Things to Consider**
Guideline of information needed:
1. Where are you in the experience? (Just loaded up, was in the office, was at the control booth, etc)
_Control booth_
2. What object/item specifically are we thinking of adjusting? (Handle on the deck, button at the office, barrel at the tower)
_Decrease the length of the pull on the switch/ handle in the control booth.  As it stand, the user has to pull the switch into the path of the teleportation spot, meaning they have to pull it into a space they  are co-located in._
3. Is this a time based adjustment? (Between the first and second train we need 5 extra seconds)
_No_
4. Is this a bug? (I get stuck between training and the first train) Please fill out the bug template instead, that can be found [at the bug template](https://github.com/vmasc-odu/Virginia-Philosophy-Reality-Lab/issues/new?assignees=JShull&labels=bug&template=bug---crash-report.md&title=) :grey_exclamation:
_No_

**Additional context**
It may also help to move the teleportation spot back from the control board a little bit.

**Comment by JShull** [comment]
This has been fixed - in the current development branch I am working on. 
Decreased the pull from 90 degrees to 60 degrees, you have to pass 40 for it to register as a "full pull"
