### ISSUE TITLE
Qualtrics Number Support

### ISSUE THREAD

**Issue by JShull** [vmasc-odu/Virginia-Philosophy-Reality-Lab#8]
**Describe the Adjustment**
Make it so Qualtrics works within button pushing

**Things to Consider**
Spend a minute looking into how Qualtrics generates random numbers - maybe I can adjust this but if not just accept any 6 digit number as we are going to have to filter on this anyways for clarity purposes
Solved by using last 6 numbers of qualtric user number.

**Azure Requirements**

1. Need to add Cosmos DB table for easy look up/add. When a user inputs their number and hits submit - we query Cosmos for this number, if it doesn't exist - add it and grant them access.
2. If it does exist - update computer screen with information to contact us if this is an error - mail to Link to our group email. Automatically prompt new output narrative/text about how to contact us for this problem.
3. Need to add developer key option to let us/others through the experience without keying a code.

**Comment by JShull** [comment]
@Kisselphil can you point me to where in the Qualtrics survey code is the random number being generated? I cannot find it.

**Comment by Kisselphil** [comment]
When you’re looking at the survey, click “Survey Flow”.  The first field there “set embedded data” is where the random number is assigned.

**Comment by Kisselphil** [comment]
Gotcha, I’ll check it out, I think you’re right

**Comment by JShull** [comment]
We agreed to run the last 5/6 numbers of the user qualtrics user ID @Kisselphil is looking into implement this. I am updating the issue to include the Azure requirements needed to implement a quick "has this number already been entered before" check and a way to inform the user if it has.

**Comment by JShull** [comment]
We will accept any 6 digit number - this just goes straight to our storage solution and we will check it later on the backend.
